<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260325065607 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE assigned_mesocycle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE NOT NULL, end_date DATE DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, mesocycle_id INT NOT NULL, athlete_id INT NOT NULL, assigned_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F809389712C12F16 ON assigned_mesocycle (mesocycle_id)');
        $this->addSql('CREATE INDEX IDX_F8093897FE6BCB8B ON assigned_mesocycle (athlete_id)');
        $this->addSql('CREATE INDEX IDX_F80938976E6F1246 ON assigned_mesocycle (assigned_by_id)');
        $this->addSql('ALTER TABLE assigned_mesocycle ADD CONSTRAINT FK_F809389712C12F16 FOREIGN KEY (mesocycle_id) REFERENCES mesocycle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assigned_mesocycle ADD CONSTRAINT FK_F8093897FE6BCB8B FOREIGN KEY (athlete_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assigned_mesocycle ADD CONSTRAINT FK_F80938976E6F1246 FOREIGN KEY (assigned_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE assigned_mesocycle DROP CONSTRAINT FK_F809389712C12F16');
        $this->addSql('ALTER TABLE assigned_mesocycle DROP CONSTRAINT FK_F8093897FE6BCB8B');
        $this->addSql('ALTER TABLE assigned_mesocycle DROP CONSTRAINT FK_F80938976E6F1246');
        $this->addSql('DROP TABLE assigned_mesocycle');
    }
}
