<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260325070533 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE set_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, set_number INT NOT NULL, reps INT DEFAULT NULL, rir INT DEFAULT NULL, weight DOUBLE PRECISION DEFAULT NULL, time_duration INT DEFAULT NULL, distance DOUBLE PRECISION DEFAULT NULL, kcal INT DEFAULT NULL, rest_time_seconds INT DEFAULT NULL, observacion TEXT DEFAULT NULL, logged_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, workout_log_id INT NOT NULL, session_exercise_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F797630DF0E44248 ON set_log (workout_log_id)');
        $this->addSql('CREATE INDEX IDX_F797630D156D8B6D ON set_log (session_exercise_id)');
        $this->addSql('CREATE TABLE workout_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(20) NOT NULL, current_exercise_id INT DEFAULT NULL, athlete_id INT NOT NULL, workout_session_id INT NOT NULL, assigned_mesocycle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6F5B68DFE6BCB8B ON workout_log (athlete_id)');
        $this->addSql('CREATE INDEX IDX_6F5B68DD1BA355 ON workout_log (workout_session_id)');
        $this->addSql('CREATE INDEX IDX_6F5B68DF05E6FE2 ON workout_log (assigned_mesocycle_id)');
        $this->addSql('ALTER TABLE set_log ADD CONSTRAINT FK_F797630DF0E44248 FOREIGN KEY (workout_log_id) REFERENCES workout_log (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE set_log ADD CONSTRAINT FK_F797630D156D8B6D FOREIGN KEY (session_exercise_id) REFERENCES session_exercise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workout_log ADD CONSTRAINT FK_6F5B68DFE6BCB8B FOREIGN KEY (athlete_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workout_log ADD CONSTRAINT FK_6F5B68DD1BA355 FOREIGN KEY (workout_session_id) REFERENCES workout_session (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workout_log ADD CONSTRAINT FK_6F5B68DF05E6FE2 FOREIGN KEY (assigned_mesocycle_id) REFERENCES assigned_mesocycle (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE set_log DROP CONSTRAINT FK_F797630DF0E44248');
        $this->addSql('ALTER TABLE set_log DROP CONSTRAINT FK_F797630D156D8B6D');
        $this->addSql('ALTER TABLE workout_log DROP CONSTRAINT FK_6F5B68DFE6BCB8B');
        $this->addSql('ALTER TABLE workout_log DROP CONSTRAINT FK_6F5B68DD1BA355');
        $this->addSql('ALTER TABLE workout_log DROP CONSTRAINT FK_6F5B68DF05E6FE2');
        $this->addSql('DROP TABLE set_log');
        $this->addSql('DROP TABLE workout_log');
    }
}
