<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260328071033 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE daily_heart_rate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, resting_heart_rate INT DEFAULT NULL, calories_out INT DEFAULT NULL, zones JSON DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_794383B5A76ED395 ON daily_heart_rate (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_daily_heart_rate_user_date ON daily_heart_rate (user_id, date)');
        $this->addSql('CREATE TABLE fitbit_activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fitbit_log_id VARCHAR(64) NOT NULL, date DATE NOT NULL, name VARCHAR(150) NOT NULL, duration_minutes INT NOT NULL, calories INT DEFAULT NULL, steps INT DEFAULT NULL, distance DOUBLE PRECISION DEFAULT NULL, average_heart_rate INT DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9B3ED3D1A76ED395 ON fitbit_activity (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_fitbit_activity_user_log ON fitbit_activity (user_id, fitbit_log_id)');
        $this->addSql('CREATE TABLE fitbit_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, access_token TEXT NOT NULL, refresh_token TEXT NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, granted_scopes JSON NOT NULL, is_valid BOOLEAN NOT NULL, connected_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A95A8856A76ED395 ON fitbit_token (user_id)');
        $this->addSql('CREATE TABLE sleep_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, duration_minutes INT NOT NULL, efficiency INT DEFAULT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, stages JSON DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3316ED0DA76ED395 ON sleep_log (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_sleep_log_user_date ON sleep_log (user_id, date)');
        $this->addSql('ALTER TABLE daily_heart_rate ADD CONSTRAINT FK_794383B5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fitbit_activity ADD CONSTRAINT FK_9B3ED3D1A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fitbit_token ADD CONSTRAINT FK_A95A8856A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sleep_log ADD CONSTRAINT FK_3316ED0DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE daily_steps ADD source VARCHAR(20) DEFAULT \'manual\' NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE daily_heart_rate DROP CONSTRAINT FK_794383B5A76ED395');
        $this->addSql('ALTER TABLE fitbit_activity DROP CONSTRAINT FK_9B3ED3D1A76ED395');
        $this->addSql('ALTER TABLE fitbit_token DROP CONSTRAINT FK_A95A8856A76ED395');
        $this->addSql('ALTER TABLE sleep_log DROP CONSTRAINT FK_3316ED0DA76ED395');
        $this->addSql('DROP TABLE daily_heart_rate');
        $this->addSql('DROP TABLE fitbit_activity');
        $this->addSql('DROP TABLE fitbit_token');
        $this->addSql('DROP TABLE sleep_log');
        $this->addSql('ALTER TABLE daily_steps DROP source');
    }
}
