<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260325211935 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE daily_steps (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, steps INT DEFAULT 0 NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B4036BA6A76ED395 ON daily_steps (user_id)');
        $this->addSql('ALTER TABLE daily_steps ADD CONSTRAINT FK_B4036BA6A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD profile_picture_filename VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE mesocycle ADD daily_steps_target INT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE daily_steps DROP CONSTRAINT FK_B4036BA6A76ED395');
        $this->addSql('DROP TABLE daily_steps');
        $this->addSql('ALTER TABLE mesocycle DROP daily_steps_target');
        $this->addSql('ALTER TABLE "user" DROP profile_picture_filename');
    }
}
