<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260325061118 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE coach_athlete (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, coach_id INT NOT NULL, athlete_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7BEB6B693C105691 ON coach_athlete (coach_id)');
        $this->addSql('CREATE INDEX IDX_7BEB6B69FE6BCB8B ON coach_athlete (athlete_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_coach_athlete ON coach_athlete (coach_id, athlete_id)');
        $this->addSql('ALTER TABLE coach_athlete ADD CONSTRAINT FK_7BEB6B693C105691 FOREIGN KEY (coach_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE coach_athlete ADD CONSTRAINT FK_7BEB6B69FE6BCB8B FOREIGN KEY (athlete_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE coach_athlete DROP CONSTRAINT FK_7BEB6B693C105691');
        $this->addSql('ALTER TABLE coach_athlete DROP CONSTRAINT FK_7BEB6B69FE6BCB8B');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE coach_athlete');
    }
}
