<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260325064506 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE mesocycle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, coach_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_81A88D353C105691 ON mesocycle (coach_id)');
        $this->addSql('CREATE TABLE session_exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_index INT NOT NULL, series_type VARCHAR(50) NOT NULL, target_sets INT NOT NULL, target_reps INT DEFAULT NULL, target_weight DOUBLE PRECISION DEFAULT NULL, superseries_group INT DEFAULT NULL, workout_session_id INT NOT NULL, exercise_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2576B574D1BA355 ON session_exercise (workout_session_id)');
        $this->addSql('CREATE INDEX IDX_2576B574E934951A ON session_exercise (exercise_id)');
        $this->addSql('CREATE TABLE workout_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, order_index INT NOT NULL, day_of_week INT DEFAULT NULL, mesocycle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC82B97C12C12F16 ON workout_session (mesocycle_id)');
        $this->addSql('ALTER TABLE mesocycle ADD CONSTRAINT FK_81A88D353C105691 FOREIGN KEY (coach_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session_exercise ADD CONSTRAINT FK_2576B574D1BA355 FOREIGN KEY (workout_session_id) REFERENCES workout_session (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session_exercise ADD CONSTRAINT FK_2576B574E934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workout_session ADD CONSTRAINT FK_AC82B97C12C12F16 FOREIGN KEY (mesocycle_id) REFERENCES mesocycle (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE mesocycle DROP CONSTRAINT FK_81A88D353C105691');
        $this->addSql('ALTER TABLE session_exercise DROP CONSTRAINT FK_2576B574D1BA355');
        $this->addSql('ALTER TABLE session_exercise DROP CONSTRAINT FK_2576B574E934951A');
        $this->addSql('ALTER TABLE workout_session DROP CONSTRAINT FK_AC82B97C12C12F16');
        $this->addSql('DROP TABLE mesocycle');
        $this->addSql('DROP TABLE session_exercise');
        $this->addSql('DROP TABLE workout_session');
    }
}
