<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260325113658 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE body_measurement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, measurement_date DATE NOT NULL, weight_kg NUMERIC(5, 2) DEFAULT NULL, chest_cm NUMERIC(5, 2) DEFAULT NULL, waist_cm NUMERIC(5, 2) DEFAULT NULL, hips_cm NUMERIC(5, 2) DEFAULT NULL, arms_cm NUMERIC(5, 2) DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, athlete_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E574BF11FE6BCB8B ON body_measurement (athlete_id)');
        $this->addSql('CREATE INDEX idx_body_measurement_athlete_date ON body_measurement (athlete_id, measurement_date)');
        $this->addSql('ALTER TABLE body_measurement ADD CONSTRAINT FK_E574BF11FE6BCB8B FOREIGN KEY (athlete_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE body_measurement DROP CONSTRAINT FK_E574BF11FE6BCB8B');
        $this->addSql('DROP TABLE body_measurement');
    }
}
