<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260328221606 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create analytics_snapshot table and add set_log composite index';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE analytics_snapshot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, module VARCHAR(50) NOT NULL, computed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, period_start DATE NOT NULL, period_end DATE NOT NULL, payload JSON NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_76E268A2A76ED395 ON analytics_snapshot (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_analytics_snapshot_user_module ON analytics_snapshot (user_id, module)');
        $this->addSql('ALTER TABLE analytics_snapshot ADD CONSTRAINT FK_76E268A2A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_set_log_workout_logged ON set_log (workout_log_id, logged_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX idx_set_log_workout_logged');
        $this->addSql('ALTER TABLE analytics_snapshot DROP CONSTRAINT FK_76E268A2A76ED395');
        $this->addSql('DROP TABLE analytics_snapshot');
    }
}
